accounts/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from django.urls import include, re_path, path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('login/',
    auth_views.LoginView.as_view(template_name='accounts/login.html'),
    name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.SignUp.as_view(), name='signup'),
]

posts/urls.py
from os import name
from django.conf.urls import url
from django.urls.resolvers import URLPattern
from . import views

app_name = 'posts'

urlpatterns = [
    url(r'^$', views.PostList.as_view(),name ='all'),
    url(r'new/$', views.CreatePost.as_view(), name='create'),
    url(r'by/(?P<username>[-\w]+)', views.UserPosts.as_view(), name='for_user'),
    url(r'by/(?P<username>[-\w]+)/(?P<pk>\d+)/$', views.PostDetail.as_view(), name='single'),
    url(r'delete/(?P<pk>\d+)/$', views.DeletePost.as_view(), name ='delete')
]

socialsite/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.urls import include, re_path, path
from . import views


urlpatterns = [
    re_path(r'^admin/', admin.site.urls),
    re_path(r'^$', views.HomePage.as_view(), name='home'),
    re_path(r'^accounts/', include('accounts.urls', namespace='accounts')),
    re_path(r'^accounts/', include('django.contrib.auth.urls')),
    re_path(r'^test/$', views.TestPage.as_view(), name='test'),
    re_path(r'^thanks/$', views.ThanksPage.as_view(), name='thanks'),
    re_path(r'^posts/', include('posts.urls', namespace='posts')),
    re_path(r'^groups/', include('groups.urls', namespace='groups')),
]

templates/base.html
<!DOCTYPE html>
{% load static %}
<html>

<head>
    <meta charset="utf-8">
    <title>Start Social</title>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">


    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>


    <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">


    <link rel="stylesheet" href="{% static 'simplesocial/css/master.css'%}">

</head>

    <body>

        <nav class="navbar mynav " role="navigation" id="navbar">
            <div class="container">
                <a class="navbar-brand mynav" href="{% url 'home' %}">Star Social</a>
                <ul class="nav navbar-nav navbar-right">
                    {% if user.is_authenticated %}
                        <li><a href="{% url 'posts:create' %}">Post</a></li>
                        <li><a href="{% url 'groups:all' %}">Groups</a></li>
                        <li><a href="{% url 'groups:create' %}">Create Group</a></li>
                        <li><a href="{% url 'accounts:logout' %}">Log Out</a></li>
                    {% else %}
                        <li><a href="{% url 'groups:all' %}">Groups</a></li>
                        <li><a href="{% url 'accounts:login' %}">Log In</a></li>
                        <li><a href="{% url 'accounts:signup' %}">Sign Up</a></li>
                    {% endif %}    
                </ul>    
            </div>
        </nav>

        <div class="container mycontent">
            
            {% block content %}
            
            {% endblock %}

        </div>
        <script type="text/javascript" src="{% static 'simplesocial/js/master.js' %}">
        </script>
    </body>
</html>

templates/index.html
{% extends "base.html" %}

{% block content %}
    <h1>Welcom to star social</h1>
{% endblock  %}

templates/test.html
{% extends "base.html" %}
{% block content %}
<h1>You are now logged in!</h1>

{% endblock %}

templates/thanks.html
{% extends "base.html" %}
{% block content %}
<h1>Thanks for visiting, come back soon!</h1>

{% endblock %}